/* AUTO-GENERATED by build-branches.js - edit branches-data.js instead. */
window.SARAB_BRANCHES = [
   {
      "id": "new-york",
      "city": "New York",
      "state": "NY",
      "name": "Sarab New York - Madison Avenue (Flagship)",
      "address": "1420 Madison Avenue, New York, NY 10029",
      "phone": "+1 (212) 555-0134",
      "tel": "+12125550134",
      "hours": "Wed - Thu 9 AM - 10 PM - Fri - Sat 9 AM - 11 PM - Sun 11 AM - 9 PM",
      "mapUrl": "https://www.google.com/maps/search/?api=1&query=1420%20Madison%20Avenue%2C%20New%20York%2C%20NY%2010029"
   },
   {
      "id": "los-angeles",
      "city": "Los Angeles",
      "state": "CA",
      "name": "Sarab Los Angeles - Sunset Boulevard",
      "address": "7420 Sunset Boulevard, Los Angeles, CA 90046",
      "phone": "+1 (323) 555-0142",
      "tel": "+13235550142",
      "hours": "Daily 10 AM - 12 AM",
      "mapUrl": "https://www.google.com/maps/search/?api=1&query=7420%20Sunset%20Boulevard%2C%20Los%20Angeles%2C%20CA%2090046"
   },
   {
      "id": "chicago",
      "city": "Chicago",
      "state": "IL",
      "name": "Sarab Chicago - River North",
      "address": "1180 North State Street, Chicago, IL 60610",
      "phone": "+1 (312) 555-0187",
      "tel": "+13125550187",
      "hours": "Wed - Sun 9 AM - 11 PM",
      "mapUrl": "https://www.google.com/maps/search/?api=1&query=1180%20North%20State%20Street%2C%20Chicago%2C%20IL%2060610"
   },
   {
      "id": "houston",
      "city": "Houston",
      "state": "TX",
      "name": "Sarab Houston - Westheimer",
      "address": "2450 Westheimer Road, Houston, TX 77098",
      "phone": "+1 (713) 555-0119",
      "tel": "+17135550119",
      "hours": "Daily 10 AM - 12 AM",
      "mapUrl": "https://www.google.com/maps/search/?api=1&query=2450%20Westheimer%20Road%2C%20Houston%2C%20TX%2077098"
   },
   {
      "id": "miami",
      "city": "Miami Beach",
      "state": "FL",
      "name": "Sarab Miami - Ocean Drive",
      "address": "861 Ocean Drive, Miami Beach, FL 33139",
      "phone": "+1 (305) 555-0164",
      "tel": "+13055550164",
      "hours": "Daily 10 AM - 1 AM",
      "mapUrl": "https://www.google.com/maps/search/?api=1&query=861%20Ocean%20Drive%2C%20Miami%20Beach%2C%20FL%2033139"
   },
   {
      "id": "atlanta",
      "city": "Atlanta",
      "state": "GA",
      "name": "Sarab Atlanta - Midtown",
      "address": "1050 Peachtree Street NE, Atlanta, GA 30309",
      "phone": "+1 (404) 555-0128",
      "tel": "+14045550128",
      "hours": "Wed - Sun 9 AM - 11 PM",
      "mapUrl": "https://www.google.com/maps/search/?api=1&query=1050%20Peachtree%20Street%20NE%2C%20Atlanta%2C%20GA%2030309"
   },
   {
      "id": "seattle",
      "city": "Seattle",
      "state": "WA",
      "name": "Sarab Seattle - Belltown",
      "address": "2101 Fourth Avenue, Seattle, WA 98121",
      "phone": "+1 (206) 555-0173",
      "tel": "+12065550173",
      "hours": "Wed - Sun 9 AM - 10 PM",
      "mapUrl": "https://www.google.com/maps/search/?api=1&query=2101%20Fourth%20Avenue%2C%20Seattle%2C%20WA%2098121"
   },
   {
      "id": "austin",
      "city": "Austin",
      "state": "TX",
      "name": "Sarab Austin - Congress Avenue",
      "address": "600 Congress Avenue, Austin, TX 78701",
      "phone": "+1 (512) 555-0196",
      "tel": "+15125550196",
      "hours": "Daily 10 AM - 12 AM",
      "mapUrl": "https://www.google.com/maps/search/?api=1&query=600%20Congress%20Avenue%2C%20Austin%2C%20TX%2078701"
   }
];
